"""UI Screens — MCP tools + the one write path from the panel into Content/Verse.

The screen catalogue lives in the same per-project store as everything else, under
the top-level ``uiScreens`` key (and ``uiTheme`` for the palette). ``merge_defaults``
passes unknown top-level keys through untouched, so nothing here needs a defaults
entry — the panel seeds the catalogue on first open.

Codegen deliberately lives in the panel (``ui/js/rgd/ui/06-verse.js``) and not here:
one generator, driven by the same tree the preview draws, so the preview and the
emitted Verse cannot drift. These tools expose the tree so an agent can read a
screen's exact layout, and ``ui_write_verse`` lets the panel land the generated
files in the project.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .store_io import _project_root

#: Only ever write Verse under here — never anywhere else in the project.
_VERSE_ROOT = "Content/Verse"

#: node type -> Verse widget class, mirrored from ui/js/rgd/ui/02-model.js.
VERSE_WIDGET = {
    "canvas": "canvas",
    "overlay": "overlay",
    "stack": "stack_box",
    "text": "text_block",
    "rect": "color_block",
    "image": "texture_block",
    "material": "material_block",
    "button": "button",
}


def _state() -> dict[str, Any]:
    from .register import _ensure_state

    return _ensure_state()


def _save(state: dict[str, Any]) -> None:
    from .register import _save as saver

    saver(state)


def _screens() -> list[dict[str, Any]]:
    st = _state()
    screens = st.get("uiScreens")
    if not isinstance(screens, list):
        screens = []
        st["uiScreens"] = screens
    return screens


def _find(screen_id: str) -> dict[str, Any] | None:
    return next((s for s in _screens() if s.get("id") == screen_id), None)


def _summary(s: dict[str, Any]) -> dict[str, Any]:
    verse = s.get("verse") or {}
    return {
        "id": s.get("id"),
        "name": s.get("name"),
        "stage": s.get("stage"),
        "category": s.get("category"),
        "status": s.get("status"),
        "widgets": _count_nodes(s.get("root")),
        "verse_path": "%s/%s/%s" % (_VERSE_ROOT, verse.get("folder", ""), verse.get("file", "")),
        "verse_class": verse.get("klass"),
    }


def _count_nodes(node: Any) -> int:
    if not isinstance(node, dict):
        return 0
    return 1 + sum(_count_nodes(c) for c in node.get("children") or [])


def _binds(node: Any, out: list[dict[str, Any]] | None = None) -> list[dict[str, Any]]:
    out = [] if out is None else out
    if isinstance(node, dict):
        if node.get("bind"):
            out.append(
                {
                    "name": node["bind"],
                    "verse_type": VERSE_WIDGET.get(node.get("type"), "widget"),
                    "widget": node.get("name"),
                }
            )
        for c in node.get("children") or []:
            _binds(c, out)
    return out


# --------------------------------------------------------------------------- #
# panel RPC
# --------------------------------------------------------------------------- #
_GENERATED_MARKER = "Generated by the Roguelike Design Platform"


def ui_write_verse(files: list[dict[str, Any]] | None = None, **_kwargs: Any) -> dict[str, Any]:
    """Write panel-generated Verse into the project, jailed to Content/Verse.

    Refuses to overwrite an existing file that lacks the generated-header marker
    so hand-written interactive devices (skill_tree_ui_device, etc.) survive
    UI Screens → Write to project.
    """
    root = _project_root()
    if not root:
        return {"ok": False, "error": "no UEFN project is open"}
    base = Path(root).resolve()
    written: list[str] = []
    skipped: list[str] = []
    for f in files or []:
        rel = str((f or {}).get("path") or "").replace("\\", "/").strip().lstrip("/")
        content = (f or {}).get("content")
        if not rel or not isinstance(content, str):
            return {"ok": False, "error": "each file needs a path and string content"}
        if not rel.startswith(_VERSE_ROOT + "/") or not rel.endswith(".verse"):
            return {"ok": False, "error": "refusing to write outside %s: %s" % (_VERSE_ROOT, rel)}
        if rel.endswith(".digest.verse"):
            return {"ok": False, "error": "digests are read-only: %s" % rel}
        dest = (base / rel).resolve()
        if base not in dest.parents:
            return {"ok": False, "error": "path escapes the project: %s" % rel}
        if dest.is_file():
            try:
                existing = dest.read_text(encoding="utf-8")
            except OSError:
                existing = ""
            if _GENERATED_MARKER not in existing:
                skipped.append(rel)
                continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        written.append(rel)
    return {"ok": True, "written": written, "skipped": skipped, "project": str(base)}


# --------------------------------------------------------------------------- #
# MCP tools
# --------------------------------------------------------------------------- #
def register_ui_tools(api: Any) -> None:
    api.register_panel_rpc("ui_write_verse", ui_write_verse)

    @api.tool()
    def rgd_ui_list_screens(stage: str = "", category: str = "", status: str = "") -> dict:
        """List designed UI screens (id, name, loop stage, category, Verse target).

        stage: boot | hub | run | combat | popup | end. Filters are optional.
        """
        rows = _screens()
        if stage:
            rows = [s for s in rows if s.get("stage") == stage]
        if category:
            rows = [s for s in rows if s.get("category") == category]
        if status:
            rows = [s for s in rows if s.get("status") == status]
        return {"count": len(rows), "screens": [_summary(s) for s in rows]}

    @api.tool()
    def rgd_ui_get_screen(screen_id: str) -> dict:
        """Full widget tree for one screen, plus its runtime-bound widgets.

        The tree maps 1:1 onto Verse UI: node.type -> widget class, node.slot ->
        canvas_slot (aMin/aMax/off/align/z/stc) when the parent is a canvas, or
        overlay_slot / stack_box_slot (h/v/pad/dist) otherwise. Offsets follow UMG:
        per axis, anchor min == max means Offsets L/T is the position and R/B is the
        size; otherwise they are insets from each anchor edge.
        """
        s = _find(screen_id)
        if not s:
            return {"error": "screen not found: " + screen_id}
        out = dict(_summary(s))
        out["notes"] = s.get("notes") or ""
        out["binds"] = _binds(s.get("root"))
        out["root"] = s.get("root")
        return out

    @api.tool()
    def rgd_ui_update_screen(
        screen_id: str,
        name: str = "",
        stage: str = "",
        category: str = "",
        status: str = "",
        notes: str = "",
        verse_folder: str = "",
        verse_file: str = "",
    ) -> dict:
        """Update a screen's metadata. Layout edits belong in the panel's designer."""
        s = _find(screen_id)
        if not s:
            return {"error": "screen not found: " + screen_id}
        if name:
            s["name"] = name
        if stage:
            s["stage"] = stage
        if category:
            s["category"] = category
        if status:
            s["status"] = status
        if notes:
            s["notes"] = notes
        verse = s.setdefault("verse", {})
        if verse_folder:
            verse["folder"] = verse_folder.strip("/")
        if verse_file:
            base = verse_file[:-6] if verse_file.endswith(".verse") else verse_file
            verse["file"] = base + ".verse"
            verse["klass"] = base
        _save(_state())
        return {"ok": True, "screen": _summary(s)}

    @api.tool()
    def rgd_ui_delete_screen(screen_id: str) -> dict:
        """Remove a screen from the catalogue. Does not delete generated .verse files."""
        st = _state()
        before = len(_screens())
        st["uiScreens"] = [s for s in _screens() if s.get("id") != screen_id]
        if len(st["uiScreens"]) == before:
            return {"error": "screen not found: " + screen_id}
        _save(st)
        return {"ok": True, "deleted": screen_id, "remaining": len(st["uiScreens"])}

    @api.tool()
    def rgd_ui_get_theme() -> dict:
        """The shared UI palette and type scale. Screens reference token ids, not hexes."""
        st = _state()
        theme = st.get("uiTheme")
        if not isinstance(theme, dict):
            return {
                "ok": True,
                "using": "panel defaults",
                "hint": "Open the UI Screens tab and edit the theme to persist an override.",
            }
        return {"ok": True, "theme": theme}

    @api.tool()
    def rgd_ui_set_theme_color(token: str, hex_value: str) -> dict:
        """Retint every screen at once by overriding one palette token, e.g. accent=#4C8DFF."""
        h = (hex_value or "").strip().lstrip("#").upper()
        if len(h) != 6 or any(c not in "0123456789ABCDEF" for c in h):
            return {"error": "hex_value must be RRGGBB"}
        st = _state()
        theme = st.setdefault("uiTheme", {})
        if not isinstance(theme, dict):
            theme = {}
            st["uiTheme"] = theme
        theme.setdefault("colors", {})[token] = "#" + h
        _save(st)
        return {"ok": True, "token": token, "value": "#" + h}
